// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCtND-NV_eKQASMksMIqEFVQUy-M_3dDE',
    appId: '1:1040823718714:web:9b99fdd885ea47d114b603',
    messagingSenderId: '1040823718714',
    projectId: 'ride-hailing-d819c',
    authDomain: 'ride-hailing-d819c.firebaseapp.com',
    storageBucket: 'ride-hailing-d819c.appspot.com',
    measurementId: 'G-BFEVS4TCY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEDLwNsrT2WRYnjd_I1SDOhrPZs2h07aY',
    appId: '1:1040823718714:android:89ebb71bc30672b914b603',
    messagingSenderId: '1040823718714',
    projectId: 'ride-hailing-d819c',
    storageBucket: 'ride-hailing-d819c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByF20TBbVsprhEgAEPz_9iVWC8YAki5tc',
    appId: '1:1040823718714:ios:a55cf6f08b1d291f14b603',
    messagingSenderId: '1040823718714',
    projectId: 'ride-hailing-d819c',
    storageBucket: 'ride-hailing-d819c.appspot.com',
    iosBundleId: 'com.cymelle.hailing.customerHailing',
  );

}